### ISSUE TITLE
Add feature for all users to create "tracking" cards for pets

### ISSUE THREAD

**Issue by allison-blumenthal** [allison-blumenthal/keepet#38]
- [ ] Add button on pets page for any user to create a "tracker" (page with a counter button for a user to log how many treats have been given, times they went potty, health incidents, etc.)
- [ ] Would then route to a "tracking" page that maps through "tracking" cards
- [ ] Clickable cards that render dynamic "tracker" pages
