### ISSUE TITLE
Create milestones, issues tickets, and project board

### ISSUE THREAD

**Issue by allison-blumenthal** [allison-blumenthal/keepet#5]
- [x] Create all milestones in Github
- [x] Add issue tickets for each feature 
- [x] Link and create a project board to track progress
